version: '3.8'

services:
  # Laravel Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khabarchin-app
    ports:
      - "9000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  # MySQL 8 Service
  mysql:
    image: mysql:8
    container_name: khabarchin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: khabarchin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "13306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
